version: '3'

services:
  basoweb:
    network: baso
    image: ${GITBASE}/basoweb
    ports:
      - "8668:8668"
    environment:
      BASOACT: basoweb
    volumes:
#      - ./data:/data
      - ./logs:/tmp/logs
