version: '3'

services:
  basoweb:
    image: ${GITBASE}/basoweb
    ports:
      - "8668:8668"
    environment:
      BASOACT: basoweb

  basoback_hy:
    image: ${GITBASE}/basoback_hy
    ports:
      - "8603:8603"
    environment:
      BASOACT: basoback_hy
      REPODIR: /mnt/baso/.repo
    volumes:
      - $(pwd)/.repo/:/mnt/baso/.repo
      